### PR TITLE
Update _postinstall.js

### PR DESCRIPTION
**Pull request by koshkin-ccna**
fix Call for peace wording

### CODE REVIEW

**Comment by jidckii** [comment]
Добавь Путина в ревьюверы, это поможет...

**Review by medikoo — APPROVED** [review]
Thank you! It looks indeed bit better

**Review by jtitov — COMMENTED** [review]
Why was silent 8 years ago?
Remove this muck, this is an open project!

**Comment by koshkin-ccna** [comment]
> Why was silent 8 years ago? Remove this muck, this is an open project!

https://github.com/medikoo/es5-ext/blob/main/LICENSE#L9
You are welcome to leave Yury @jtitov

**Comment by medikoo** [comment]
For all the discussions please see https://github.com/medikoo/es5-ext/issues/116

**Pull request merged**
