### PR TITLE
Fix native sticky regexp support detection

### PR DESCRIPTION
**Pull request by mathiasbynens**
https://github.com/tc39/ecma262/issues/262
https://github.com/tc39/ecma262/pull/263
https://bugs.chromium.org/p/v8/issues/detail?id=4617

### CODE REVIEW

**Comment by medikoo** [comment]
Looks great, Thank you!

**Comment by mathiasbynens** [comment]
Could you please release a new version including this fix? Thanks!

**Comment by medikoo** [comment]
It'll be shortly on.

Still, doesn't same issue apply to `unicode` flag? -> https://github.com/medikoo/es5-ext/blob/master/reg-exp/%23/unicode/is-implemented.js

If it's the case, I'd like to fix that as well before publishing

**Comment by mathiasbynens** [comment]
Good point! #42

**Comment by medikoo** [comment]
Published as v0.10.11

**Pull request merged**
